---
datadog_site: "datadoghq.com"
datadog_agent_major_version: "7"
datadog_api_rate_per_second: "200"
datadog_nomad_openmetrics_namespace: "nomad"
datadog_nomad_openmetrics_endpoint: "http://127.0.0.1:4646/v1/metrics?format=prometheus"
