---
nomad_version: 1.7.3
nomad_zip_url: "https://releases.hashicorp.com/nomad/1.7.3/nomad_1.7.3_linux_arm64.zip"
nomad_zip_tmp_path: "/tmp/nomad_1.7.3_linux_arm64.zip"

# Test bootstrap for autoscaler multi-namespace feature.
nomad_create_test_namespaces: true
nomad_test_namespaces:
  - ns1
  - ns2
