---
nomad_version: "1.8.15+ent"
nomad_zip_url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version | replace('+', '%2B') }}_linux_arm64.zip"
nomad_zip_tmp_path: "/tmp/nomad_{{ nomad_version | replace('+', '_') }}_linux_arm64.zip"
