---
- name: Configure Nomad servers
  hosts: nomad_servers
  become: true
  roles:
    - nomad_server

- name: Configure Nomad clients
  hosts: nomad_clients
  become: true
  roles:
    - nomad_client

- name: Configure Prometheus
  hosts: prometheus
  become: true
  roles:
    - prometheus
