---
influxdb_docker_image: "influxdb:1.8"
influxdb_data_dir: "/var/lib/influxdb"
influxdb_retention: "7d"  # 7 days retention for test data

# Authentication settings
influxdb_auth_enabled: true
influxdb_admin_user: "admin"
influxdb_admin_password: "admin_secure_password"
influxdb_telegraf_user: "telegraf"
influxdb_telegraf_password: "telegraf_password"
influxdb_autoscaler_user: "autoscaler"
influxdb_autoscaler_password: "autoscaler_password"
