---
- name: Configure base host resolution
  hosts: all
  become: true
  roles:
    - base

- name: Configure Consul servers
  hosts: nomad_servers
  become: true
  roles:
    - consul

- name: Configure Consul clients
  hosts: nomad_clients
  become: true
  roles:
    - consul

- name: Configure Nomad servers
  hosts: nomad_servers
  become: true
  roles:
    - nomad_server

- name: Configure Nomad clients
  hosts: nomad_clients
  become: true
  roles:
    - nomad_client

- name: Configure Datadog agents
  hosts: nomad_servers:nomad_clients
  become: true
  roles:
    - datadog

- name: Configure Nomad Autoscaler
  hosts: nomad_servers
  become: true
  roles:
    - nomad_autoscaler
