{
  "all": {
    "vars": {
      "ansible_user": "root",
      "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
    },
    "children": {
      "nomad_servers": {
        "hosts": {
          "server-vm-0": {
            "ansible_host": "192.168.139.185",
            "ansible_port": 22
          },
          "server-vm-1": {
            "ansible_host": "192.168.139.127",
            "ansible_port": 22
          },
          "server-vm-2": {
            "ansible_host": "192.168.139.142",
            "ansible_port": 22
          }
        }
      },
      "nomad_clients": {
        "hosts": {
          "client-vm-0": {
            "ansible_host": "192.168.139.216",
            "ansible_port": 22
          },
          "client-vm-1": {
            "ansible_host": "192.168.139.103",
            "ansible_port": 22
          },
          "client-vm-2": {
            "ansible_host": "192.168.139.98",
            "ansible_port": 22
          }
        }
      },
      "prometheus": {
        "hosts": {
          "prometheus-vm": {
            "ansible_host": "192.168.139.97",
            "ansible_port": 22
          }
        }
      }
    }
  }
}
