{
  "all": {
    "vars": {
      "ansible_user": "root",
      "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
    },
    "children": {
      "nomad_servers": {
        "hosts": {
          "server-vm-0": {
            "ansible_host": "192.168.139.48",
            "ansible_port": 22
          },
          "server-vm-1": {
            "ansible_host": "192.168.139.121",
            "ansible_port": 22
          },
          "server-vm-2": {
            "ansible_host": "192.168.139.13",
            "ansible_port": 22
          }
        }
      },
      "nomad_clients": {
        "hosts": {
          "client-vm-0": {
            "ansible_host": "192.168.139.72",
            "ansible_port": 22
          },
          "client-vm-1": {
            "ansible_host": "192.168.139.151",
            "ansible_port": 22
          },
          "client-vm-2": {
            "ansible_host": "192.168.139.53",
            "ansible_port": 22
          }
        }
      },
      "prometheus": {
        "hosts": {
          "prometheus-vm": {
            "ansible_host": "192.168.139.145",
            "ansible_port": 22
          }
        }
      }
    }
  }
}
