{
  "all": {
    "vars": {
      "ansible_user": "root",
      "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
    },
    "children": {
      "nomad_servers": {
        "hosts": {
          "server-vm-0": {
            "ansible_host": "192.168.139.224",
            "ansible_port": 22
          },
          "server-vm-1": {
            "ansible_host": "192.168.139.220",
            "ansible_port": 22
          },
          "server-vm-2": {
            "ansible_host": "192.168.139.29",
            "ansible_port": 22
          }
        }
      },
      "nomad_clients": {
        "hosts": {
          "client-vm-0": {
            "ansible_host": "192.168.139.219",
            "ansible_port": 22
          },
          "client-vm-1": {
            "ansible_host": "192.168.139.17",
            "ansible_port": 22
          },
          "client-vm-2": {
            "ansible_host": "192.168.139.85",
            "ansible_port": 22
          }
        }
      },
      "prometheus": {
        "hosts": {
          "prometheus-vm": {
            "ansible_host": "192.168.139.78",
            "ansible_port": 22
          }
        }
      }
    }
  }
}
