---
nomad_autoscaler_binary_local: "{{ playbook_dir }}/../../bin/nomad-autoscaler"
nomad_autoscaler_install_path: "/usr/local/bin/nomad-autoscaler"
nomad_autoscaler_config_dir: "/etc/nomad-autoscaler"
nomad_autoscaler_log_dir: "/var/log/nomad-autoscaler"
nomad_server_address: "http://127.0.0.1:4646"
prometheus_apm_address: "http://prometheus-vm.orb.local:9090"
