---
ansible_user: root

consul_version: 1.17.0
consul_zip_url: "https://releases.hashicorp.com/consul/1.17.0/consul_1.17.0_linux_arm64.zip"
consul_zip_tmp_path: "/tmp/consul_1.17.0_linux_arm64.zip"


prometheus_version: 2.50.1
prometheus_archive_url: "https://github.com/prometheus/prometheus/releases/download/v2.50.1/prometheus-2.50.1.linux-arm64.tar.gz"
prometheus_archive_tmp_path: "/tmp/prometheus-2.50.1.linux-arm64.tar.gz"
prometheus_extract_dir: "/tmp/prometheus-2.50.1.linux-arm64"
