---
- name: Replace OrbStack resolv.conf symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Configure DNS resolvers
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    mode: "0644"
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8

- name: Configure hosts file for OrbStack VM name resolution
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
